version: '3.5'

services:
  ticketbeast:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: ticketbeast
    depends_on:
      - mysql-db
    ports:
      - 8000:80
      - 80:80
      - 443:443
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
      - ./run/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      backend:
        aliases:
          - app

  ticket-admin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: ticket-admin
    restart: always
    ports:
      - '8080:80'
      - '445:443'
    volumes:
      - ./run/httpd/phpmyadmin.conf:/etc/apache2/sites-available/000-default.conf
      - ./run/certs:/etc/apache2/ssl
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: securerootpassword
    networks:
      backend:
        aliases:
          - ticket-admin

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
      - ./run/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network